openapi: 3.0.3
info:
  title: Ensi Comments Service
  contact:
    name: API Support
    url: https://ensi.tech/contacts
    email: mail@greensight.ru
  version: 1.0.0
  description: Ensi Comments Service
servers:
  - url: /api/v1
tags:
  - name: comments
    description: Комментарии
paths:
  /comments/by-post/{code}:
    get:
      tags:
        - comments
      operationId: listByPost
      x-lg-handler: 'App\Http\ApiV1\Controllers\CommentsController@listByPost'
      x-lg-route-name: 'listByPost'
      x-lg-skip-request-generation: true
      summary: Получить все комментарии для поста по его коду
      description: Получить все комментарии для поста по его коду
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
          description: Код поста
      responses:
        "200":
          description: Успешный ответ
          content:
           application/json:
             schema:
               $ref: './comments.yaml#/CommentListResponse'
        "500":
          $ref: '#/components/responses/ServerError'


components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
